name: Run Playwright Tests

on:
  push:
    branches: [ master ]  # Trigger the workflow on push to main branch
  pull_request:
    branches: [ master ]  # Trigger the workflow on pull request to main branch
  schedule:
    - cron: '15 9 * * 1'  # Trigger the workflow at 3 PM UTC from Monday to Friday
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  test:
    timeout-minutes: 160  # Set a timeout for the job of 160 minutes
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Use the latest version of the checkout action to check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Use the latest version of the setup-node action to set up Node.js
        with:
          node-version: '20.10.0'  # Specify the Node.js version to use

      - name: Install dependencies
        run: npm ci  # Use npm ci to install dependencies, ensuring a clean state by removing node_modules before installing

      - name: Install Playwright
        run: npx playwright install --with-deps  # Install Playwright and its dependencies along with necessary browsers

      - name: Install Browsers
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx playwright test --workers=2  # Run Playwright tests and generate JSON report

      - name: Archive test results
        if: failure()  # Upload the Playwright report artifact only if the job fails
        uses: actions/upload-artifact@v4  # Use the latest version of the upload-artifact action
        with:
          name: playwright-report  # Name the artifact
          path: playwright-report/  # Specify the path to the artifact
          retention-days: 30  # Retain the artifact for 30 days